# Site Settings
title: Hyemi's Blog | Web Developer
email: leehyemi0468@gmail.com
description: Portfolio & Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leehyemi0468.github.io/index.html" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Hyemi's Blog 
user_description: Some text about you.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: leehyemi0468
facebook_username: facebook_username
instagram_username: instagram_username
linkedin_username: linkedin_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
